apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pythonexecutor
  name: pythonexecutor
spec:
  containers:
  - image: pythonexecutor
    imagePullPolicy: Never
    name: pythonexecutor
    ports:
    - containerPort: 5000
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "60m"
      requests:
        memory: "100Mi"
        cpu: "50m"
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pythonexecutor
  name: pythonexecutor
spec:
  selector:
    run: pythonexecutor
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer