apiVersion: v1
kind: Service
metadata:
    name: python-executor-back-service
spec:
    selector:
         app: python-executor-back
    type: NodePort
    ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30003
      protocol: TCP